### ISSUE TITLE
Nachweis bei unterschiedlichen Orten

### ISSUE THREAD

**Issue by sudousername** [Digitaler-Impfnachweis/documentation#1]
Impfungen welche bei unterschiedlichen Ärzt:innen ; Ländern / Impfzentren durchgeführt wurden müssen für die Qualifizierung berücksichtigt werden. Einheitlicher Nachweis ist nicht immer möglich.

**Comment by SZoerner** [comment]
Hallo @sudousername. Da hast du Recht - was wir versuchen ist, uns durch Standards und Integratoren dem anzunähern. Hast du hierzu eine konkrete Frage?
