### ISSUE TITLE
Publish Source Code of the website

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/documentation#10]
Please publish the source code of the website https://digitaler-impfnachweis-app.de.
It would be great if it would be possible to edit the site here on GitHub and it's automatically deployed, similar to the www.coronawarn.app website (https://github.com/corona-warn-app/cwa-website).

**Comment by jleufgen** [comment]
Hi, thanks for your feedback! The souce code is not shown on the website, as the open source can be viewed in GitHub. 
Best regards!

**Comment by rugk** [comment]
Where exactly? On https://github.com/Digitaler-Impfnachweis no repository is shown that contains this source code as far as I see.
Maybe you still have set a repository to private instead of public visibility?

**Comment by Ein-Tim** [comment]
@jleufgen 

My enhancement request wasn't to show the source code on the website but to publish a GitHub repository with the source code of the website, to allow community contributors to create PRs, issues, etc.

**Comment by Ein-Tim** [comment]
I won't just let this request "die", please reopen this issue as it was closed due to a misunderstanding of my request. 

Thank you!

**Comment by jleufgen** [comment]
Hi @Ein-Tim you can view the source code of the website with any browser.
It is a purely content/ informative website. There are no functions for the whole vaccination certificate thing on the website - only information is given here.

**Comment by Ein-Tim** [comment]
@jleufgen 

Thank you! I know this, but still I suggest to publish a GitHub Repository which contains the code so that changes on the website (especially the FAQ) can be made by community contributors through PRs.

**Comment by jleufgen** [comment]
@Ein-Tim Unfortunately, the source code of the website https://www.digitaler-impfnachweis-app.de/ cannot be published on GitHub. The website is not an open source project, but is maintained in its own CMS. Therefore, generally no pull requests can be submitted. If you have further comments about the website, please feel free to send an email to: support@covpassapp.de.

**Comment by Ein-Tim** [comment]
@jleufgen Okay, thats, as you say, unfortunate, but thanks for clarifying. If I spot anything I'll email you. 

Thanks for the reply!

Closing.
