### ISSUE TITLE
Translate the app into other languages

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/documentation#12]
The app seems to be only available in German at the moment. This should be changed as soon as possible
At least an English translation should be added, afterwards more languages should follow. 
I'm sure the community would help to translate into other languages.

**Comment by Ein-Tim** [comment]
PR trying to add English localization under iOS: https://github.com/Digitaler-Impfnachweis/covpass-ios/pull/28

**Comment by jleufgen** [comment]
Hello, thanks for the feedback! The English translation will come with the next release, further translations are not planned for now.
