### ISSUE TITLE
Why does CovPass (not CovPassCheck) require internet/network access?

### ISSUE THREAD

**Issue by treysis** [Digitaler-Impfnachweis/documentation#14]
The app itself reads the QR from the certificate and also displays this QR code. Why does it need internet/network access for this? I am not talking about CovPassCheck, which obviously DOES need internet (at least from time to time to check the validity of issuer's certificates).

**Comment by l1m3r** [comment]
I second that question and additionally would like to know why the CovPass app requires the rights to "run at startup" and "deactivate sleep mode" (on android).

It's not answered in the [technical details](https://www.digitaler-impfnachweis-app.de/technische-details/) or the [FAQ](https://www.digitaler-impfnachweis-app.de/faq/) and using a search engine produces too much white noise.


Word cloud: covpass android app berechtigungen why warum

**Comment by timokoenig** [comment]
CovPass and CovPassCheck both need internet access to update the local trust list which is required for the signature validation. We do not accept certificates with an invalid signature. In those cases the CovPass app will show an error and does not save the certificate on the device, and the CovPassCheck app will show an error result view.

**Comment by treysis** [comment]
Thx for the insight. Since the paper-based QR-code can still be used (or used in CWA, which doesn't check trust list) even if the trust for a certificate has become invalid, wouldn't it be sufficient if the trust list was only updated in the CovPassCheck-App? Instead, you could still update the list in CovPass by integrating it with regular app updates.

I do understand that CovPassCheck-App does need an internet connection for that purpose.

**Comment by wkornewald** [comment]
We use Android's WorkManager to update the trust list in the background once every day, so even if you're offline you're pretty much guaranteed to have an up-to-date trust list. The [Android WorkManager docs](https://developer.android.com/reference/androidx/work/package-summary) provide more detail about the required permissions:

```
 WorkManager uses the following permissions:

    android.permission.WAKE_LOCK to make it can keep the device awake to complete work before API 23
    android.permission.ACCESS_NETWORK_STATE to listen to network changes before API 23 and monitor network Constraints
    android.permission.RECEIVE_BOOT_COMPLETED to listen to reboots and reschedule work properly.
```

**Comment by treysis** [comment]
thx @wkornewald, I am just saying it wouldn't be necessary to update the trust list in CovPass in-app. It would work fine without it, since evaluation is done with CovPassCheck. It would be sufficient to update the trust list through regular app updates over the app stores. No network permission would be needed for the CovPass-App.

**Comment by wkornewald** [comment]
The other question whether CovPass should even validate the scanned QR code at all is a trade-off of helping the user to avoid mistakes vs. not requiring these permissions. Countries can revoke certificates and having the feedback that the validation will indeed succeed and you won't be denied at the entrance is a UX improvement and also it makes manipulation slightly more difficult.

Now you can debate that it's more important to not use these permissions, but on the other hand you can see in the source code that these permissions are only used in good faith.

**Comment by treysis** [comment]
Agreed. Also, I didn't see that you finally published the source 👍.

**Comment by jleufgen** [comment]
Hi all :) Has the question been resolved?
