### ISSUE TITLE
Android app can not scan certificates from the corona warn app

### ISSUE THREAD

**Issue by Ondolin** [Digitaler-Impfnachweis/documentation#15]
The Android app is not capable of scanning the corona verification QR-Code given by the "corona warn app".

## How to reproduce the error

1. Register a "Digital Proof of Vaccine" in the corona warn app
2. Open the CovPass Check app on an android device
3. Scan the code
4. Nothing happens

**Comment by Ein-Tim** [comment]
@oliver-steinbrecher I know you don't answer here but this is an important issue. Please have a look at it.

**Comment by oliver-steinbrecher** [comment]
Where and when did you receive the initial qrcode?

**Comment by EricHier** [comment]
We received the initial qr code today from a local pharmacy. @Ondolin and me both got our qr code(s) today and tested the apps together.

**Comment by timokoenig** [comment]
@Ondolin we fixed a couple issues in the recent Android versions. Could you retry it with version 1.16.4, please?

**Comment by Ondolin** [comment]
With this version everything works perfekt. Thanks for your help. I'll close this issue now.
