### ISSUE TITLE
How can I ensure that my personal data is deleted after the signing process?

### ISSUE THREAD

**Issue by redundancer** [Digitaler-Impfnachweis/documentation#16]
My personal data will be sent to a central server for the signing process. How can I ensure that this data will be erased after the signature process? And why do strangers have access to my data?

**Comment by Ein-Tim** [comment]
And even more, how can I ensure that the person scanning my QR-Code doesn't take a screenshot of the QR-Code and thus has my full name and dob?

**Comment by treysis** [comment]
You can't. Same as anyone looking at your ID with the naked eye.

**Comment by Ein-Tim** [comment]
@treysis 

This is something completely else.
Imagine a situation where a person is standing on the entrance of a club and is scanning the DCC QR codes. After each scan, he/she takes a screenshot. Nobody notices, nobody cares. Afterwards he sells the data to anyone, with the name you can sometimes find out where the person lives or what phone number they have. 

If somebody is checking my id card, he would probably need photographic memory to remember this all. Or would you be able to remember 100 full names and date of births if you have the id card for less than a minute?

**Comment by fynngodau** [comment]
Indeed, for the digital certificate you could additionally store the date of vaccination and the vaccine. For someone checking this on paper, it would be necessary for them to take notes, which one would notice, or they could only remember the data for very few people.

**Comment by treysis** [comment]
In that case, you can't prevent it. You have to rely on the lawful acting of those people.

**Comment by jleufgen** [comment]
Has the topic been resolved?

**Comment by jleufgen** [comment]
Hi, there are two ways to generate DCC. One is via the web frontend in IZ/Praxis where no personal data is sent to the backend, only the hash to be signed. When using the plaintext API the data is sent, but only held in RAM for the process of creating the DCC and then discarded immediately. The transmission is necessary for checking schema and correctness. No personal information is persisted in any case. This was a requirement of the client and has also been verified by the BSI.
