### ISSUE TITLE
Android and Iphone are showing two different dates for status 'fully vaccinated" 

### ISSUE THREAD

**Issue by Platzhoersch** [Digitaler-Impfnachweis/documentation#17]
Example with my own QR-Code:
Android: 16.06.2021
Ipone: 15.06.2021

**Comment by Ein-Tim** [comment]
Related to https://github.com/Digitaler-Impfnachweis/certification-apis/issues/91

**Comment by timokoenig** [comment]
There is a new iOS version in the AppStore (v 1.0.2) @Platzhoersch can you check it with that version, please?

**Comment by Platzhoersch** [comment]
@timokoenig Sure, I updated. But since yesterday the status switched in both app to "Vollständiger Impfschutz". Thus, I can't check the identical estimated date anymore.

**Comment by Platzhoersch** [comment]
Did a check with the QR of my wife, who got her second shot today. Android and IPhone are now showing the same date.

**Comment by Platzhoersch** [comment]
Seems to work now. Compare last comment.
