### ISSUE TITLE
Improve FAQ entry "Ab wann gilt der vollständige Impfschutz?"

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/documentation#20]
The FAQ entry "Ab wann gilt der vollständige Impfschutz?" currently says: 

> In Deutschland gelten Personen als geschützt, die mit einem in der EU zugelassenen COVID-19-Impfstoff geimpft wurden und bei denen nach Gabe der letzten Impfstoffdosis mindestens 14 Tage vergangen sind.

Some people might think that they reach the full vaccination protection on day 14 after the last shot, but they only do on day 15. I suggest to "[…] mindestens 14 Tage vergangen sind, also am 15. Tag."

**Comment by jleufgen** [comment]
It's communicated everywhere 14 days, so we stick to that in our FAQ as well so there's no confusion.

**Comment by Ein-Tim** [comment]
Okay, but isn't it more confusing for the user if everywhere it says 14 days but in the app it actually takes 15?
