### ISSUE TITLE
["CovPass Check": Offline mode & WLAN]: "Internet connection required" although available ...

### ISSUE THREAD

**Issue by Jo-Achim** [Digitaler-Impfnachweis/documentation#22]
Hello,

I have a little understanding problem... and I think, it's a bug...
If “CovPass Check” is not used for some time (days), the message “! Internet connection required" is displayed (e.g. on today's July 22nd, 2021 with a reference to the last update on July 17th, 2021 21:06).

Why is an existing WLAN connection not automatically used for the update when "CovPass Check" is started?

Best regards, Joachim.

Cross reference: Why "CovPass" and "CovPass Check" need an internet connection (https://github.com/Digitaler-Impfnachweis/documentation/issues/14#issuecomment-862737985). 

E.g. Android 11 (One UI 3.1) with Android security update: 01. Juli 2021 / 01. August 2021
Samsung Galaxy Note 10, SM-N970F/DS
"CovPass Check": v1.28.4 / 1.72.4
**Internet via WLAN only!**

**Comment by jleufgen** [comment]
Hello, we have also tested this specific case once. With 3 days without app usage. Smartphone had wifi connection throughout. "! Internet connection required" was not displayed. 
Have you experienced the problem again?
Best regards!

**Comment by Jo-Achim** [comment]
@jleufgen, thanks for asking.

With the newer versions (currently CovPassCheck v1.95.12 (Android)) I have not noticed the above problem again. Neither on a Samsung Note 10 (Android 11) nor on a Nokia 7.2 (Android 10).

I thank you and thus close this problem.

Best regards, Joachim.
