### ISSUE TITLE
Issuing a certificate of former COVID-19 infection as a local health authority / Als Gesundheitsamt Genesenenzertifikate ausstellen

### ISSUE THREAD

**Issue by ophcode** [Digitaler-Impfnachweis/documentation#24]
Hallo!

1) Ist es derzeit möglich, als Gesundheitsamt Genesenenzertifikate auszustellen (Nicht an Telematikinfrastruktur/TI-Netz angebunden)?
2) Wenn nein: Ist es beabsichtigt, eine Schnittstlle für den ÖGD zu implementieren?

Hintergrund:
Als Gesundheitsamt bekommen wir die positiven PCR-Befunde für Bürger:innen in unserer Zuständigkeit zugesandt.
Derzeit verschicken wir nach Genesung/Ende der Quarantänezeit eine Email / einen Brief mit Nachweis über die Genesung in Textform - um den digitalen Nachweis zu bekommen, müssen die Bürger:innen damit noch zur Hausärztin oder zur Apotheke.
Eine Möglichkeit, unserem Genesenenbescheid einen QR-Code für die CovSaveApp / CWA hinzuzufügen, würde diesen Prozess vereinfachen und die Nutzung der Apps vereinfachen.

**Comment by jleufgen** [comment]
Hallo ophcode, 
die Gesundheitsämter befinden sich aktuell im Onboarding. Das Gesundheitsamt sollte von seinem Landesministerium informiert worden sein.
