### ISSUE TITLE
Is it true that looking at a certificate is sufficient for validating it? 

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/documentation#25]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Question has not already been asked in another issue

## Your Question
Your FAQ states this:
<img width="1236" alt="Bildschirmfoto 2021-09-10 um 11 52 27" src="https://user-images.githubusercontent.com/67682506/132835813-8d72f2da-f881-4a86-8369-c8aaa3d522ff.png">

To me, this sounds like it is sufficient to look at a certificate, read the data from it and cross check it with an ID document to validate that somebody was vaccinated agains or recovered from COVID-19 or tested negative for it. Is this true?
Doesn't the CovPassCheck-App does more? Like checking the signature, etc. 

If this is true, other people might wonder why CovPassCheck was developed if it has no advantage over just looking at the certificate.

**Comment by guerda** [comment]
Thanks Tim for raising this issue. I think this faq entry is quite misleading. I already had one location owner state that the RKI says that the check with the app is not required and therefore they don't scan the certificates. 

I have never experienced a location yet where the qr code was scanned. They only read the texts below and trust the "magic black and white image" 😒

**Comment by zimbosmurf** [comment]
Apparently this answer was quietly removed from the FAQ!

**Comment by guerda** [comment]
Good catch! At least the misleading answer is gone. A clarifying answer how the certificates _should_ be checked is still missing though.

**Comment by Ein-Tim** [comment]
Thanks for the hint @zimbosmurf!

I guess this means that either the FAQ entry was very misleading or just wrong 😅

I'll leave this open for clarification.

**Comment by jleufgen** [comment]
Thank you for finding the bug, we have already removed it. We are currently working on making the CovPassCheck app more prominent so that it is used more often.

**Comment by guerda** [comment]
To be honest it's good that the check app feys more promotion. I would recommend to make the guidelines more transparent and more clearly stated: when does an owner of a restaurant have to scan the certificates?

**Comment by guerda** [comment]
Well that is a bummer, i thought that it was just not transparent.
So basically the whole responsibility lies with the owners of restaurants, clubs, etc how to verify the vaccination proof?

**Comment by molk-ibm** [comment]
Who else can be responsible here? The tool(s) for verification are freely available.
The CovPassCheck App runs on a wide range of (even cheap) devices.
A passing verification is worth as much as the check of an Id matching the holder of the DCC.
This is an effort that needs to be taken by restaurants that might be forced to close otherwise.
Currently there is no law I know of effectively enforcing these validations, though.

Coming back to the initial question:
No, just "looking" at the DCC (aka QR Code) is not enough.
Checking the validity with a free tool like the CovPassCheck App
combined with a verification of the DCC holder is.

**Comment by ndegendogo** [comment]
> Currently there is no law I know of effectively enforcing these validations, though.

As long as we don't have such a law, a restaurant could take this responsibility *on a voluntary base*, but as you said, there is no legal obligation to do so.
So they can weight the pros and cons:
- expenses to buy these devices, and effort on the procedure to check
- will their customer appreciate the reduced risk? Or will they even be discouraged by these procedures?

A law could really help here. Like with all regulations regarding safety of work conditions, minimum wages, environmental aspects during production, and the like.

**Comment by guerda** [comment]
The missing law is really problem. My inquiry with the Bundesgesundheitsministerium is still unanswered after weeks.

**Comment by ndegendogo** [comment]
> My inquiry with the Bundesgesundheitsministerium

@guerda thanks for going through the effort of this inquiry.
*Why does BMG even spend this much money on development of these apps, if they are not in usage later?*

**Comment by molk-ibm** [comment]
CovPass is in use - not as broad as it should/could be, but that is a common issue we have in our society handling this pandemic.
CovPass Check .... well see above.
