### ISSUE TITLE
Website issue: FAQ entry „How do I get the EU Digital COVID Certificate“ translates „Corona-Warn-App“ as „Corona warning app“

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/documentation#26]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [ ] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/Digitaler-Impfnachweis/covpass-android)
    * [iOS repository](https://github.com/Digitaler-Impfnachweis/covpass-ios) 
**Bug affects the website**
* [X] Bug is not already reported in another issue

## Technical details

Irrelevant.

## Describe the bug

The English FAQ entry "How do I get the EU Digital COVID Certificate translated "Corona-Warn-App" as "Corona warning app". This is not how the app's called and thus this should be corrected. 

## Steps to reproduce the issue

1. Open https://www.digitaler-impfnachweis-app.de/en/faq/#general-questions
2. Scroll down to the above mentioned FAQ entry
3. Read the FAQ entry and note the phrase "Corona warning app" at the end.

## Expected behaviour

"Corona-Warn-App" should be "Corona-Warn-App" in English and not "Corona warning app".

## Possible Fix

Change the text.

**Comment by jleufgen** [comment]
Thanks for the hint! The bug will be fixed today.

**Comment by jleufgen** [comment]
Done
