### ISSUE TITLE
Please mention our open source solution on your website

### ISSUE THREAD

**Issue by ManuelB** [Digitaler-Impfnachweis/documentation#3]
Hi,
we are currently building an open source solution for PVS systems and maybe pharmacies to be able to use the API from the certification service:
 
https://github.com/ere-health/covid-19-green-certificate

The toughest implementation detail is the OpenID Connect dance using the SMC-B. This is implemented here:
https://github.com/ere-health/ere-ps-app/blob/feature/covid-19-green-digital-certificates/src/main/java/health/ere/ps/service/idp/IdPService.java

Please mention us on your pages to get this out as fast as possible.

/Manuel

**Comment by jleufgen** [comment]
Hi, thanks for your feedback! The souce code is not shown on the website, as the open source can be viewed in GitHub. Best regards!
