### ISSUE TITLE
License should not be modified

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/documentation#30]
Your [LICENSE](https://github.com/Digitaler-Impfnachweis/documentation/blob/main/LICENSE) is modified, see the issue https://github.com/Digitaler-Impfnachweis/covpass-android/issues/140 for further information. 

The change which was done in line 189 should be reverted.

**Comment by jleufgen** [comment]
fixed

**Comment by MikeMcC399** [comment]
@jleufgen 

You have closed this issue with no change having been done.

https://github.com/Digitaler-Impfnachweis/documentation/blob/e7a94992899da99d2b544fc2e9fba28a1516ae69/LICENSE#L189

should be reverted to the original license template with the text:

"Copyright [yyyy] [name of copyright owner]"

**Comment by oliver-steinbrecher** [comment]
Sorry I mixed up the repositories :)  I updated https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/LICENSE

**Comment by oliver-steinbrecher** [comment]
Correctly fixed now ! Thanks for pointing this out.
