### ISSUE TITLE
Recovery Time was changed by RKI to 90 days instead of 180 days

### ISSUE THREAD

**Issue by jona7o** [Digitaler-Impfnachweis/documentation#31]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Question has not already been asked in another issue

## Your Question
Hi beginning from Saturday the recovery date must be smaller than 90 days instead of the signed 180 days in the eudgc. What will happen with the recovery certificates which are already issued? Will the RKI revoke the used certificates every day, so that the covpass check app knows which recovery pass is valid?

```
"eudgc": {
        "r": [
            {
               ...
                "du": "2022-04-13", // <--- Will every cert
               ...
            }
        ],....
....
```

**Comment by Ein-Tim** [comment]
Hi @jona7o!

Did you take a look at https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/97?
