### ISSUE TITLE
Verrifier non-ephemeral possibility

### ISSUE THREAD

**Issue by watmm** [Digitaler-Impfnachweis/documentation#4]
Hi all, though that doesn't look like many.
Can someone please address these questions:
https://github.com/corona-warn-app/cwa-documentation/issues/615

**Comment by jleufgen** [comment]
Hi, the question has already been answered, isn't it?

**Comment by watmm** [comment]
Hi Julia,

Not really, but I have since learned that I can just use the existing yellow vaccination booklet, so feel free to close.

**Comment by jleufgen** [comment]
Ok, thank you for your answer!
