### ISSUE TITLE
Availability in different regions than Germany

### ISSUE THREAD

**Issue by snoato** [Digitaler-Impfnachweis/documentation#5]
The app is only available in the German Apple App Store. Many EU-nationals who are only staying in Germany for a couple of years (e.g. students) and still have bank accounts etc. in their home countries won't switch their App Store region because the process is involved. It requires cancelling all subscriptions and using up all credit (from prepaid gift cards).

It would only be sensible to release the app in all EU App Stores, to give access to EU nationals living in Germany.

**Comment by treysis** [comment]
+1.
This excludes most migrant workers/expats, international students, repatriates, and many others that use 'foreign' app stores for different reasons. As many are also from non-EU countries (e.g. USA, China, India...) the app should be published without limiting it to specific localized app stores at all. The app store location is just an arbitrary marketing setting and has no legal implications.

**Comment by franzgoetschel** [comment]
Same accounts for Android mobiles. I cannot download the app.
 "dieser Artikel ist in deinem Land nicht verfügbar". Ich bin nicht der Einzige, der sein Handy in der Schweiz (oder sonst im Ausland) zugelassen hat, aber in Deutschland wohnt. Bitte beheben.

**Comment by jmerck** [comment]
Für deutsche Bürger die im Ausland sich geimpft haben, sollte es die Möglichkeit geben, dies In der App zu melden, bzw. die App erstmal runterladen zu können.

**Comment by treysis** [comment]
@jmerck Man sollte die App einfach runterladen können, egal wo man geimpft wurde und welche Staatsbürgerschaft man besitzt. Nur die Erstellung des QR-Codes sollte lokal/regional geregelt sein.

**Comment by jmerck** [comment]
Ja, finde ich auch. Sorry!!

**Comment by SGrosse-Holz** [comment]
Seconding this issue, would be great to see a fix soon

**Comment by apphancer** [comment]
Same issue here. Using an iPhone linked with the UK AppleStore (i.e. non-EU), and unable to register a German certificate as someone living in Germany.

**Comment by antoniocascais** [comment]
Facing same issue here.

I have my Google play account set for Portugal and can't install this app.

**Comment by Smit-tay** [comment]
Indeed !

This seems like just more unnecessary German Engineering to me.
Don't get me wrong, I live and work in Germany, and admire the culture here.  BUT, the German propensity to unnecessarily complicate things is sometimes quite difficult to deal with.

**Comment by cdraeger** [comment]
My girlfriend and other people I know have just been running into this, forcing me to build the app for her locally.. but who else can usually do this? Any non-native German is currently excluded from installing and using this app, although they legally live here.

Please remove this obstacle. Anyone from the EU should be able to install this application, changing the app store is restricted and has other implications like already mentioned (bank accounts in home countries etc.).

It'd be preferred that the app also falls back to English, I believe it was really just developed with German strings? But ok, that can be dealt with separately, installing it in the first place is more important.

**Comment by franzgoetschel** [comment]
I did download it from here.But that should not be necessary having to look
for such a kind of copies . What a shame ..


https://covpass.de.malavida.com/android/#gref


cdraeger ***@***.***> schrieb am Mo., 28. Juni 2021, 11:59:

**Comment by treysis** [comment]
> My girlfriend and other people I know have just been running into this, forcing me to build the app for her locally..

You can use any PlayStore APK mirror site, downloader, or even copy the APK from your phone. No need to compile it yourself. Or use Corona-Warn-App for the time beeing.

> It'd be preferred that the app also falls back to English, I believe it was really just developed with German strings? But ok, that can be dealt with separately, installing it in the first place is more important.

AFAIK currently only German strings. But there are also other German-speaking countries: Austria, Switzerland, Belgium.

**Comment by ntfc** [comment]
Another alternative download method for the time being can be through aurora store as described [AuroraOSS/AuroraStore#668](https://gitlab.com/AuroraOSS/AuroraStore/-/issues/668#note_612943289)

**Comment by cdraeger** [comment]
> You can use any PlayStore APK mirror site, downloader, or even copy the APK from your phone. No need to compile it yourself. Or use Corona-Warn-App for the time being.

Yes of course, I could and I am aware of these options. But that's not the point really in this ticket.

**Comment by Smit-tay** [comment]
I have to say, only fools download APK from random sites.  

What makes you think you can trust any 3rd party ?  Hell , I barely trust Google

**Comment by treysis** [comment]
@Smit-tay Experience. Nothing foolish about that.

**Comment by apphancer** [comment]
> I have to say, only fools download APK from random sites.
Why are you so sure about that?

**Comment by treysis** [comment]
Can we finally get someone assigned to this issue?! @wkornewald

**Comment by Cazaimi** [comment]
> > My girlfriend and other people I know have just been running into this, forcing me to build the app for her locally..
> 
> You can use any PlayStore APK mirror site, downloader, or even copy the APK from your phone. No need to compile it yourself. Or use Corona-Warn-App for the time being.
> 
> > It'd be preferred that the app also falls back to English, I believe it was really just developed with German strings? But ok, that can be dealt with separately, installing it in the first place is more important.
> 
> AFAIK currently only German strings. But there are also other German-speaking countries: Austria, Switzerland, Belgium.

This only works out for Android users, and not iOS. 

Also, this issue has not even been triaged. Are the maintainers monitoring this at all? It would be really helpful to all the parties involved. I hope that this will be triaged and worked upon soon. Lastly, I am also sure that many of us would contribute and help toward solving this as well, but the process begins with triaging and assigning.

**Comment by gregreen** [comment]
There is a workaround, which is to install a different app. If I'm not mistaken, the official apps from the different European countries can all handle one another's vaccine certificates.

Both the Swiss and French apps are available in other regions (including the US Play Store). For reasons that are unclear, EU privacy laws apparently prevent the German app from being made available in the US Play Store, but they don't prevent other countries from making their apps available there.

**Comment by jleufgen** [comment]
Hello, there are currently no plans to release the app in all EU App Stores, to give access to EU nationals living in Germany. Therefore, I will close the ticket.

**Comment by Ein-Tim** [comment]
@jleufgen 

Could you please elaborate why there are no plans to do this? At least there can't be a legal reason since the Corona-Warn-App, which can also store EU DCCs, is released in all EU app stores.

**Comment by cdraeger** [comment]
It's an unfortunate decision, but I guess there are politics at play (since every country has their own app). It's probably to avoid confusion. Please, at least give the option to alternative stores and at least official APK downloads then.

**Comment by Ein-Tim** [comment]
@cdraeger Yes, could be, but still, I'd like to hear an "official" answer from @jleufgen on this.

**Comment by cdraeger** [comment]
It's also be interested in that, because isn't this statement for the iOS app contradicting? https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/4

**Comment by Ein-Tim** [comment]
@cdraeger 

https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/4#issuecomment-884158918 talks about a release in the US App Store, @jleufgen talks about a release in other EU stores, so confusing, but no contradiction IHMO (;

**Comment by cdraeger** [comment]
> @cdraeger
> 
> [Digitaler-Impfnachweis/covpass-ios#4 (comment)](https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/4#issuecomment-884158918) talks about a release in the US App Store, @jleufgen talks about a release in other EU stores, so confusing, but no contradiction IHMO (;
> Still, a more detailed official comment on this would be highly appreciated.

The original commenter talks about the US store being relevant for him/her, but the issue for other stores as well. Also the linked comment states it will likely roll out to other stores afterwards, so I do find it contradicting that on this issue it is generally declined.

Should it be the case that only EU stores are excluded, that is also unfortunate because especially in the EU many people roam freely, live and work in other EU countries (which is the point, right?). That would be politics over real-life scenarios and even more unfortunate.

**Comment by ratkins** [comment]
This is a terrible decision, and you will continue to have people telling you so until a cogent explanation of why it was made is given.

**Comment by treysis** [comment]
> This is a terrible decision, and you will continue to have people telling you so until a cogent explanation of why it was made is given.

And even worse, it will continue to stand as an example how Germany is incapable of delivering digital solutions and how supposedly data protection laws block innovation. No matter how technically perfect the app might be.

**Comment by Smit-tay** [comment]
More COVID-19 idiocy.
I guess we shouldn't be surprised.  The entire response has been little more than moronic.

**Comment by jleufgen** [comment]
It is not currently prioritized by the customer because the CWA is available in EU countries.

**Comment by Ein-Tim** [comment]
And what about CovPassCheck? What is recommended there? @jleufgen
