### ISSUE TITLE
Publish Source Code of the apps

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/documentation#6]
The apps "CovPass" and "CovPassCheck" went live on the App Store and Google Play Store on 10.06.2021.
Please publish the Source Code of the apps.

**Comment by codejus** [comment]
I just can support this, especially as you state on the CovPass Website in the [FAQ](https://digitaler-impfnachweis-app.de/faq/) that the whole project is available as OpenSource so that the community can participate in the development and improvement. 
Just look at the CWA how usefull the community was especially regarding bug fixing or enchantment ideas.

**Comment by cookiengineer** [comment]
After reading the FAQ, this was the exact reason why I looked into this GitHub organization - I was assuming that there's a possibility to get an F-Droid build available or to manually build it myself (as I don't intend to use Google Play due to privacy concerns).

**Comment by danialbehzadi** [comment]
It's insane that the source code in not published yet 🤯

**Comment by Ein-Tim** [comment]
What's also insane is that the maintainer don't seem to care at all. A little answer would be sufficient for now, I understand that they have a huge workload, but just a little "We're working on this" or "We don't plan to publish the source code of the apps" wouldn't be too much, would it @oliver-steinbrecher @thinkberg?

**Comment by thinkberg** [comment]
Its stated the source code will be made public and so it will. This has nothing to do with "don't care at all". This is a very high pressure project and the first priority is to get certificates out to citizens.

**Comment by Ein-Tim** [comment]
@thinkberg I totally understand this. Thank you for your answer. This is sufficient, at least for me for now (can't speak for others here 😉).

**Comment by oliver-steinbrecher** [comment]
Source code is going to be available really soon.

**Comment by Ein-Tim** [comment]
Here we go: 

Android: https://github.com/Digitaler-Impfnachweis/covpass-android
iOS: https://github.com/Digitaler-Impfnachweis/covpass-ios

Closing as implemented. Thank you!
