### ISSUE TITLE
Only available in German app stores

### ISSUE THREAD

**Issue by treysis** [Digitaler-Impfnachweis/documentation#7]
The app is only available if you app store country is set to Germany. This excludes most expats/migrant workers, international students, and many others that use 'foreign' app stores for different reasons. The app should be published without limiting it to specific localized app stores. The app store location is just an arbitrary marketing setting and has no legal implications.

**Comment by Ein-Tim** [comment]
Same as #5

**Comment by treysis** [comment]
How did I miss this? ^^
