### ISSUE TITLE
APK download fehlt

### ISSUE THREAD

**Issue by rtslbrnft** [Digitaler-Impfnachweis/documentation#9]
Ich schildere das Problem mal als Android Benutzer. Apple etc. gilt Gleiches.

Bei einem Open Source Projekt, daß zu wesentlichen Teilen aus Steuermitteln finanziert ist sollte es eigentlich selbstverständlich sein, daß die Software nicht hinter einer Paywall liegt. Keine Monetäre, aber eine in der ich mit persönlichen Daten zahlen muss.

Dies unterstützen und fordern Sie durch den ZWANG zur Registrierung bei GOOGLE, da der Appstore keinem Download ohne registrierung zulässt.

Sollten Sie technisch nicht fähig sein, die Binaries via URL zu veröffentlichen... dann empfehle ich eine auf den fachkundigen Programmierer gerichtete Anleitung für einen vollen Build der App.

Sollte das Ganze für Sie nicht in Frage kommen wäre doch eine angemessene Begründung angemessen, warum man eine solche Einwilligung in einen Servicevertrag mit Google im Wiederspruch zu Art. 7 DSGVO Satz 4 voraussetzt.

**Comment by rugk** [comment]
I guess this is covered by https://github.com/Digitaler-Impfnachweis/documentation/issues/8

**Comment by rtslbrnft** [comment]
Not completely. My main argument is the way of ditributing the app.

If the developers or project owners decide to COMPLETELY COMPLY with the suggestions in [#8](8) then everything is covered.

If only partial or not at all, the argument still is valid also for a closed source apk.

**Comment by cdraeger** [comment]
This receives more weight now, especially since issue #5 has been closed. Other than building the app, which most cannot do, many which are not registered in the German Play Store have no official APK source. Also for security reasons I am counting on this ticket now. Uploading hot-linkable, pre-built APKs with each release here (or the official website) would be much appreciated.

**Comment by jleufgen** [comment]
Hello, it was decided against providing the Android packages (APK) to certain websites for their publication. Best regards

**Comment by cdraeger** [comment]
@jleufgen Fine with "certain websites", what about providing it here via Github? It's just a compiled release version next to the code, I don't see a reason against that.

**Comment by rugk** [comment]
…or on teh RKI website or so even, if they don't want third-parties to host it…
